name: quill_markdown
description: A quill to markdown converter and vice versa
version: 0.1.0
homepage: https://github.com/ArjanAswal/quill_markdown.git
repository: https://github.com/ArjanAswal/quill_markdown.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.13
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
